# BUILDING DATASET

In [1]:
import pandas as pd
import random

joy = [
"I feel really happy today",
"Today is a beautiful day",
"I am feeling great and relaxed",
"I just achieved something amazing",
"I love spending time with my friends",
"I feel excited about the future",
"This moment feels wonderful",
"I am proud of myself",
"Everything feels positive today",
"I feel full of energy and happiness"
]

sadness = [
"I feel very lonely today",
"Nothing seems to make me happy",
"I feel emotionally exhausted",
"I feel like crying",
"I am feeling really down",
"Today feels very heavy",
"I miss someone a lot",
"I feel empty inside",
"I am struggling with my feelings",
"I feel like nobody understands me"
]

anger = [
"I am really frustrated right now",
"This situation makes me angry",
"I cannot tolerate this anymore",
"I feel like screaming",
"I am very irritated today",
"This is so unfair",
"I feel extremely annoyed",
"I hate when things go wrong",
"This makes my blood boil",
"I am losing my patience"
]

fear = [
"I feel scared about the future",
"I am worried about what will happen",
"I feel nervous right now",
"I am afraid of failing",
"I feel anxious about tomorrow",
"I cannot stop overthinking",
"I feel uneasy and stressed",
"I am worried about everything",
"I feel insecure about my decisions",
"I am afraid something bad might happen"
]

love = [
"I care deeply about someone",
"I feel grateful for the people around me",
"I appreciate my friends a lot",
"I feel connected to people I love",
"I feel warmth in my heart",
"I feel thankful for everything",
"I cherish these moments",
"I love spending time with family",
"I feel emotionally supported",
"I feel kindness around me"
]

surprise = [
"I did not expect that at all",
"That was completely unexpected",
"I am shocked by this news",
"This surprised me a lot",
"I cannot believe what just happened",
"That was totally surprising",
"I did not see that coming",
"I am amazed by the result",
"This feels unbelievable",
"That was a big surprise"
]

data = []

for i in range(800):
    data.append([random.choice(joy), "joy"])
    data.append([random.choice(sadness), "sadness"])
    data.append([random.choice(anger), "anger"])
    data.append([random.choice(fear), "fear"])
    data.append([random.choice(love), "love"])
    data.append([random.choice(surprise), "surprise"])

df = pd.DataFrame(data, columns=["text","emotion"])

df.to_csv("emotion_dataset.csv", index=False)

print("Dataset created successfully")
print("Total rows:", len(df))

Dataset created successfully
Total rows: 4800

In [2]:
df.head()

                               text  emotion
0         I feel really happy today      joy
1            Today feels very heavy  sadness
2  I am really frustrated right now    anger
3        I cannot stop overthinking     fear
4         I feel warmth in my heart     love

In [3]:
df.shape

(4800, 2)

# NLP PREPROCESSING

In [4]:
#importing libraries 
import pandas as pd
import numpy as np
import re
import string

In [5]:
#loading dataset 
df = pd.read_csv("emotion_dataset.csv")

df.head()

                               text  emotion
0         I feel really happy today      joy
1            Today feels very heavy  sadness
2  I am really frustrated right now    anger
3        I cannot stop overthinking     fear
4         I feel warmth in my heart     love

In [6]:
# checking no. of rows and coloumns 
df.shape

(4800, 2)

In [7]:
# text cleaning function that cleans the sentences we come across 
def clean_text(text):
    
    text = text.lower()  
    
    text = re.sub(r"http\S+", "", text)  
    
    text = re.sub(r"\d+", "", text)  
    
    text = text.translate(str.maketrans("", "", string.punctuation))  
    
    text = text.strip()
    
    return text

In [8]:
# cleaning 
df["clean_text"] = df["text"].apply(clean_text)

df.head()

                               text  emotion                        clean_text
0         I feel really happy today      joy         i feel really happy today
1            Today feels very heavy  sadness            today feels very heavy
2  I am really frustrated right now    anger  i am really frustrated right now
3        I cannot stop overthinking     fear        i cannot stop overthinking
4         I feel warmth in my heart     love         i feel warmth in my heart

In [9]:
# check emotion disturbution
df["emotion"].value_counts()

emotion
joy         800
sadness     800
anger       800
fear        800
love        800
surprise    800
Name: count, dtype: int64

In [10]:
# to check dataframe 
df.head()

                               text  emotion                        clean_text
0         I feel really happy today      joy         i feel really happy today
1            Today feels very heavy  sadness            today feels very heavy
2  I am really frustrated right now    anger  i am really frustrated right now
3        I cannot stop overthinking     fear        i cannot stop overthinking
4         I feel warmth in my heart     love         i feel warmth in my heart

# CONVERTING TEXT TO NUMBERS(TF-IDF)

In [11]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\hind\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\hind\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.1)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\hind\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\hind\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\hind\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
vectorizer = TfidfVectorizer()

In [14]:
X = vectorizer.fit_transform(df["clean_text"]) # above all these converts every word into vectors

In [15]:
y = df["emotion"]

In [16]:
# training and testing data sepertion 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ML BEGINS( training emotion prediction model)

In [17]:
# starts learning emotion
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [18]:
# for checking accuracy for detection 
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 1.0

In [19]:
# detailed performance 
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       anger       1.00      1.00      1.00       155
        fear       1.00      1.00      1.00       160
         joy       1.00      1.00      1.00       149
        love       1.00      1.00      1.00       171
     sadness       1.00      1.00      1.00       168
    surprise       1.00      1.00      1.00       157

    accuracy                           1.00       960
   macro avg       1.00      1.00      1.00       960
weighted avg       1.00      1.00      1.00       960

# MOODFORDGE RESPONSE DICTIONARY

In [20]:
responses = {
    "joy": "I'm really happy to hear that. Want to share what made your day better?",
    
    "sadness": "It sounds like things might feel heavy right now. I'm here to listen if you want to talk about it.",
    
    "anger": "That sounds frustrating. Take a breath — I'm here with you. What happened?",
    
    "fear": "It seems like something is worrying you. You don't have to face it alone here.",
    
    "love": "That's really warm to hear. Moments like these are special.",
    
    "surprise": "That sounds unexpected! What happened?"
}

# MOODFORDGE AI FUNCTION

In [21]:
def moodforge_ai(user_text):
    
    cleaned = clean_text(user_text)
    
    vector = vectorizer.transform([cleaned])
    
    emotion = model.predict(vector)[0]
    
    response = responses.get(emotion, "I'm here to listen.")
    
    print("Detected Emotion:", emotion)
    print("MoodForge:", response)

# TESTING AI

In [22]:
moodforge_ai("I feel very lonely today")

Detected Emotion: sadness
MoodForge: It sounds like things might feel heavy right now. I'm here to listen if you want to talk about it.

In [23]:
moodforge_ai("Today was amazing and I feel proud")

moodforge_ai("I am really frustrated with everything")

moodforge_ai("I feel nervous about tomorrow")

Detected Emotion: joy
MoodForge: I'm really happy to hear that. Want to share what made your day better?
Detected Emotion: anger
MoodForge: That sounds frustrating. Take a breath — I'm here with you. What happened?
Detected Emotion: fear
MoodForge: It seems like something is worrying you. You don't have to face it alone here.

# INTERRACTIVE MOODFORDGE CHAT

In [24]:
# creating chat function 
def start_moodforge():

    print("🌙 MoodForge AI")
    print("A safe space to share how you feel.")
    print("Type 'exit' anytime to end the conversation.\n")

    while True:
        user_text = input("You: ")

        if user_text.lower() == "exit":
            print("MoodForge: Take care of yourself. I'm always here when you need to talk.")
            break

        cleaned = clean_text(user_text)

        vector = vectorizer.transform([cleaned])

        emotion = model.predict(vector)[0]

        response = responses.get(emotion, "I'm here to listen.")

        print("MoodForge:", response)
        print()

In [25]:
start_moodforge()

🌙 MoodForge AI
A safe space to share how you feel.
Type 'exit' anytime to end the conversation.

You:  hi exit

MoodForge: That's really warm to hear. Moments like these are special.

You:  exit

MoodForge: Take care of yourself. I'm always here when you need to talk.

In [26]:
# emotion history tracker
emotion_history = []

In [27]:
# update of cht function
def start_moodforge():

    print("🌙 MoodForge AI")
    print("A safe space to share how you feel.")
    print("Type 'exit' anytime to end the conversation.\n")

    while True:
        user_text = input("You: ")

        if user_text.lower() == "exit":
            print("MoodForge: Take care of yourself. I'm always here when you need to talk.")
            break

        cleaned = clean_text(user_text)

        vector = vectorizer.transform([cleaned])

        emotion = model.predict(vector)[0]

        emotion_history.append(emotion)

        response = responses.get(emotion, "I'm here to listen.")

        print("Detected Emotion:", emotion)
        print("MoodForge:", response)
        print()

In [ ]:
# chat again
start_moodforge()

In [ ]:
# create emotion graph
import matplotlib.pyplot as plt
from collections import Counter

emotion_counts = Counter(emotion_history)

plt.bar(emotion_counts.keys(), emotion_counts.values())

plt.title("MoodForge Emotion Analysis")
plt.xlabel("Emotion")
plt.ylabel("Frequency")

plt.show()

In [ ]:
# storing conversation
conversation_log = []

In [ ]:
# updating chat function
def start_moodforge():

    print("🌙 MoodForge AI")
    print("A safe space to share how you feel.")
    print("Type 'exit' anytime to end the conversation.\n")

    while True:
        user_text = input("You: ")

        if user_text.lower() == "exit":
            print("MoodForge: Take care of yourself. I'm always here when you need to talk.")
            break

        cleaned = clean_text(user_text)

        vector = vectorizer.transform([cleaned])

        emotion = model.predict(vector)[0]

        emotion_history.append(emotion)

        conversation_log.append({
            "message": user_text,
            "detected_emotion": emotion
        })

        response = responses.get(emotion, "I'm here to listen.")

        print("Detected Emotion:", emotion)
        print("MoodForge:", response)
        print()

In [ ]:
# chat again 
start_moodforge()

# saving conversation as diary file

In [ ]:
import pandas as pd

log_df = pd.DataFrame(conversation_log)

log_df.to_csv("moodforge_diary.csv", index=False)

print("Conversation saved as moodforge_diary.csv")

In [ ]:
# mood trend line graph 
import matplotlib.pyplot as plt

emotion_numbers = [i for i in range(len(emotion_history))]

plt.plot(emotion_numbers, emotion_history, marker='o')

plt.title("MoodForge Mood Timeline")
plt.xlabel("Conversation Step")
plt.ylabel("Emotion")

plt.show()

# SAVING TREND MODEL

In [ ]:
!pip install seaborn

In [ ]:
import pickle

with open("moodforge_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Model and vectorizer saved successfully")

In [ ]:
# creating emotion disturbution graph 
import seaborn as sns

sns.countplot(x=emotion_history)

plt.title("Emotion Distribution in Conversation")

plt.show()

In [ ]:
import pickle

with open("moodforge_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Model saved successfully")

In [ ]:
import matplotlib.pyplot as plt

plt.plot(range(len(emotion_history)), emotion_history, marker='o')

plt.title("Mood Timeline During Conversation")
plt.xlabel("Message Number")
plt.ylabel("Emotion")

plt.show()

In [ ]:
log_df

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_style("whitegrid")

sns.countplot(x=emotion_history, palette="pastel")

plt.title("MoodForge Emotion Distribution", fontsize=14)
plt.xlabel("Emotion")
plt.ylabel("Count")

plt.show()

# FRONTEND

In [ ]:
#on app.py